[package]
name = "app-properties"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-app-properties = { path = "../derive-app-properties" }
