[package]
name = "derive-app-properties"
version = "0.0.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
darling = "0.20.3"
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.65"
quote = "1.0.30"
syn = { version = "2.0.26", features = ["extra-traits"] }
